github: [Kyuk3t5uk1]
patreon: octocat
tidelift: npm/octo-package
custom: ["https://www.paypal.com/donate/?token=4-kagpZu2rfqObt9AJag4PH-0D8v92gAT9tmiYKSqynJPiImqH6PwnxgOche8hMP8SzEQ0&country.x=AU&locale.x="]
