<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_donations" />
<input type="hidden" name="business" value="Xaen24@gmail.com" />
<input type="hidden" name="item_name" value="Donations for building my website" />
<input type="hidden" name="currency_code" value="AUD" />
<input type="image" src="https://www.paypalobjects.com/en_AU/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
<img alt="" border="0" src="https://www.paypal.com/en_AU/i/scr/pixel.gif" width="1" height="1" />
</form>
https://www.paypal.com/donate/?token=4-kagpZu2rfqObt9AJag4PH-0D8v92gAT9tmiYKSqynJPiImqH6PwnxgOche8hMP8SzEQ0&country.x=AU&locale.x=
